Django_project/Django_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_app.urls')),
    path('shop/',include('shop_app.urls')),
    path('blog/',include('blog_app.urls')),
    path('contact/',include('contact_app.urls')),
    path('checkout/',include('checkout_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('product/',include('product_app.urls')),
]

Django_project/blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'
urlpatterns = [
    path('', views.blog, name = 'blog'),
]

Django_project/cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'
urlpatterns = [
    path('', views.cart, name = 'cart'),
]

Django_project/checkout_app/urls.py
from django.urls import path
from . import views

app_name = 'checkout_app'
urlpatterns = [
    path('', views.checkout, name = 'checkout'),
]

Django_project/contact_app/urls.py
from django.urls import path
from . import views

app_name = 'contact_app'
urlpatterns = [
    path('', views.contact, name = 'contact'),
]

Django_project/home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'
urlpatterns = [
    path('', views.home, name = 'home'),
]
 

Django_project/product_app/urls.py
from django.urls import path
from . import views

app_name = 'product_app'
urlpatterns = [
    path('<slug:slug>.p-<int:product_id>/', views.product_detail, name = 'product_detail'),
]
 

Django_project/shop_app/urls.py
from django.urls import path
from . import views
from product_app.views import product_detail

app_name = 'shop_app'

urlpatterns = [
    path('', views.shop, name='shop'),
    path('get_products/<str:component>/', views.get_products, name='get_products'),
    path('product/<slug:slug>.p-<int:product_id>/', product_detail, name='product_detail'),
]

Django_project/blog_app/models.py
from django.db import models

# Create your models here.

Django_project/cart_app/models.py
from django.shortcuts import render

# Create your models hear

Django_project/checkout_app/models.py
from django.db import models

# Create your models here.

Django_project/contact_app/models.py
from django.db import models

# Create your models here.

Django_project/home_app/models.py
from django.db import models

# Create your models here.

Django_project/product_app/models.py
from django.db import models

# Create your models here.

Django_project/shop_app/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock_quantity = models.IntegerField()
    img_url = models.TextField(null=True)
    Robusta = models.BooleanField()
    Arabica = models.BooleanField()
    Culi = models.BooleanField()
    slug = models.SlugField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return str(self.product_id)
    

Django_project/blog_app/views.py
from django.shortcuts import render

# Create your views here.
def blog(request):
    return render(request,'blog.html')

Django_project/cart_app/views.py
from django.shortcuts import render,redirect
from shop_app.models import Product
# Create your views here.

def cart(request):
    return render(request,'cart.html')  

Django_project/checkout_app/views.py
from django.shortcuts import render

# Create your views here.
def checkout(request):
    return render(request,'checkout.html')

Django_project/contact_app/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request,'contact.html')

Django_project/home_app/views.py
from django.shortcuts import render
from shop_app.models import Product

# Create your views here.
def home(request):
    object = Product.objects.all()
    context = {
        'products': object
    }
    return render(request,'home.html',context)

Django_project/product_app/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.urls import reverse
from shop_app.models import Product
    
def product_detail(request, slug, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    context = {
        'product': product
    }
    return render(request, 'product.html', context)

Django_project/shop_app/views.py
from django.shortcuts import render
from .models import Product
from django.http import JsonResponse

# Create your views here.
def shop(request):
    object = Product.objects.all()
    context = {
        'products': object
    }      
    
    return render(request,'shop.html',context)

def get_products(request, component):
    if component == 'robusta':
        products = Product.objects.filter(Robusta=True)
    elif component == 'arabica':
        products = Product.objects.filter(Arabica=True)
    elif component == 'culi':
        products = Product.objects.filter(Culi=True)
    else:
        products = Product.objects.all()
        
    products_data = [
        {'product_name': product.product_name, 'img_url': product.img_url, 'price': product.price, 'product_id': product.product_id, 'slug': product.slug}
        for product in products
    ]

    return JsonResponse(products_data, safe=False)

Django_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> Klei - {% block title_content%}{% endblock title_content%}</title>
    <link rel="icon" href="{% static "image/Klei logo - Circle white.png" %}" type="image/icon type">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block link_content%}{% endblock link_content %}

    <script src="https://kit.fontawesome.com/2ff7201d77.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="header">
        <a href=""><img src="{% static "image/Klei logo - Full logo black.png" %}" alt="logo" class="logo"></a>
        <div class="menu">
            <a class="menu_items" href="{% url "home_app:home" %}">Trang chủ</a>
            <a class="menu_items" href="{% url "shop_app:shop" %}">Sản phẩm</a>
            <a class="menu_items" href="">Giới Thiệu</a>
            <a class="menu_items" href="{% url "blog_app:blog" %}">Blogs</a>
            <a class="menu_items" href="{% url "contact_app:contact" %}">Liên hệ</a>
        </div>
        <a href=""><i class="fa-solid fa-magnifying-glass"></i></a>
        <a href="{% url 'cart_app:cart' %}"><i class="fa-solid fa-cart-shopping"></i></a>
        <form action="{% url "contact_app:contact" %}">
            <button class="btn_contact">Liên hệ</button>
        </form>
    </div>

    <!-- body  -->
    <div class="body">
        {% block banner%}
            <div class="section_1">
                <div class="div_banner">
                    <img src="{% static "image/banner.png"%}" alt="" class="img_banner">
                    <div class="div_content_banner">
                        Online shop
                    </div>
                </div>
            </div>
        {% endblock%}

        {% block home_content%}{% endblock home_content%}
        {% block blog_content%}{% endblock blog_content%}
        {% block checkout_content%}{% endblock checkout_content%}
        {% block contact_content%}{% endblock contact_content%}
        {% block cart_content %}{% endblock cart_content %}
        {% block product_content %}{% endblock product_content %}
        {% block shop_content %}{% endblock shop_content %}
    </div>

    <!-- footer  -->
    <div class="container-fluid footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="link_footer"><a href="" class="link_footer">Giới thiệu</a></div>
                    <div class="link_footer">
                            Kleikhan là thương hiệu cà phê từ Tây Nguyên, Việt Nam. Cùng những nhà cung cấp bền vững, tử tế và giàu năng lực - Chúng tôi giới thiệu với thế giới các sản phẩm chất lượng cao, nguyên bản và hoang dã. Bằng tư duy toàn cầu và đột phá, Kleikhan - mang vị Tây Nguyên để bạn sẵn sàng cho cuộc chiến hôm nay.
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="link_footer">
                        Klei Coffee
                    </div>
                    <div class="link_footer">
                        15A Nguyễn Trung Trực, Phường 5, Quận Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam 
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="link_footer">
                        Liên kết
                    </div>
                    <div class="link_footer">
                        <a href="" class="link_footer">Chọn quà cho nhau</a>
                    </div>
                    <div class="link_footer">
                        <a href="" class="link_footer">Tất cả sản phẩm</a>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="link_footer">
                        <a href="" class="link_footer">Hỗ trợ</a>
                    </div>
                    <div class="link_footer">
                        <a href="" class="link_footer">Giới thiệu</a>
                    </div>
                    <div class="link_footer">
                        <a href="" class="link_footer">Liên hệ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Django_project/templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Blogs
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
{% endblock link_content %}

{% block product%}{% endblock product%}

{% block blog_content%}
    <div class="container section_2">
        <div class="row">
            <div class="col-sm-8">
                <div class="post_blogs">
                    <img src="{% static "image/img_post.jpg"%}" alt="img_post" class="img_post">
                    <div class="title_post">
                        <h4>ROREM IPSUM DOLOR SIT AMET, CONSE CTETURE YEMEI..</h4>
                    </div>
                    <div class="text_post">
                        <p>Rorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a liqua. Ut enim ad minim veniam, quis nostrud exerc itaullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.ea commodo consequaty.</p>
                    </div>
                    <button class="btn_post">Read more</button>
                </div>

                <div class="post_blogs">
                    <img src="{% static "image/img_post.jpg"%}" alt="img_post" class="img_post">
                    <div class="title_post">
                        <h4>ROREM IPSUM DOLOR SIT AMET, CONSE CTETURE YEMEI..</h4>
                    </div>
                    <div class="text_post">
                        <p>Rorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna a liqua. Ut enim ad minim veniam, quis nostrud exerc itaullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.ea commodo consequaty.</p>
                    </div>
                    <button class="btn_post">Read more</button>
                </div>
            </div>

            <div class="col-sm-4">

            </div>
        </div>
    </div>
{% endblock blog_content%}

Django_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Giỏ hàng
{% endblock title_content %}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/cart.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static "js/cart.js" %}"></script>
{% endblock link_content %}

{% block cart_content%}
<div class="body">
      <div class="mid">
        <div class="mid-wrap">
          <div class="mid-title">
            <div class="product">product</div>
            <div class="price">price</div>
            <div class="quantity">quantity</div>
            <div class="subtotal">subtotal</div>
          </div>
      <div class="miditem_container">
      
      </div>
          
          <div class="mid-btn">
            <button class="btn">
              <span>Total Quantity</span>
              <span id="quantityDisplay"></span>
            </button>
            <button class="btn">
              <span>total</span>
              <span id = 'priceDisplay'>$45,00</span>
            </button>
            <a href="{% url "checkout_app:checkout" %}">
              <button class="btn brown">
                <span>procced to checkout</span>
              </button>
            </a>

            <button class="btn brown delete_cart">
              <span>Xóa giỏ hàng</span>
            </button>
          </div>
        </div>
      </div>
{% endblock cart_content%}

Django_project/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Thanh toán
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/checkout.css" %}">
{% endblock link_content %}

{% block product%}{% endblock product%}

{% block checkout_content%}
    <!-- form  -->
    <div class="container section_2">
        <div class="method_payment">
            <h2>Select payment method</h2>
            <div class="form-check-inline">
                <label for="" class="form-check-lable">
                    <input type="radio" class="form-check-input" name="method_checkout">Bank transfer
                </label>
            </div>
            <div class="form-check-inline">
                <label for="" class="form-check-lable">
                    <input type="radio" class="form-check-input" name="method_checkout">Check payment
                </label>
            </div>
            <div class="form-check-inline">
                <label for="" class="form-check-lable">
                    <input type="radio" class="form-check-input" name="method_checkout">Cash
                    </label>
            </div>
        </div>

        <div class="personal_info">
            <h2>Personal info</h2>

            <div class="row">
                <div class="col">
                    <label for="first_name">Họ:</label>
                    <input type="text" class="form-control">
                </div>
                <div class="col">
                    <label for="last_name">Tên:</label>
                    <input type="text" class="form-control">
                </div>
                <div class="col">
                    <label for="number">Số điện thoại:</label>
                    <input type="number" class="form-control">
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label for="add">Địa chỉ:</label>
                    <input type="text" class="form-control">
                </div>
                <div class="col">
                    <label for="mail">Email:</label>
                    <input type="email" class="form-control">
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label for="add_info">Lưu ý:</label>
                    <textarea name="" id="" cols="30" rows="10" class="form-control"></textarea>
                </div>
            </div>
            <div class="div_btn_checkout">
                <h5>Tổng giá trị: </h5> 
                <button class="btn_checkout">Đặt hàng</button>
            </div>
        </div>
    </div>
{% endblock checkout_content%}

Django_project/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Liên hệ
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/contact.css" %}">
{% endblock link_content %}

{% block product%}{% endblock product%}

{% block contact_content%}
    <div class="container section_2">
        <div class="row">
            <div class="col">
                <h6>Email</h6>
                <p>Israfilsupol836@gmail.com</p>
            </div>
            <div class="col">
                <h6>Location</h6>
                <p>
                    15A Nguyễn Trung Trực, Phường 5, Quận Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam
                </p>
            </div>
            <div class="col">
                <h6>Phone number</h6>
                <p> 
                    088 - 01869018907
                    <br>
                    (88) 908 675 43667
                </p>
            </div>
        </div>
        <div class="contact_form">
            <form action="">
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4"></div>
                </div>
                <div class="row row_2">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Name:">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Mail:">
                    </div>
                </div>
                <div class="row row_3">
                    <div class="col">
                        <input type="text" class="form-control" placeholder="Subject:">
                    </div>
                </div>
                <div class="row row_4">
                    <div class="col">
                        <textarea name="" id="" cols="30" rows="10" class="form-control" placeholder="Message:"></textarea>
                    </div>
                </div>
                <div class="div_btn">
                    <button class="btn_contact_form">
                        Gửi tin nhắn
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="section_3">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.231240416692!2d106.80047917471231!3d10.87000888928448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317527587e9ad5bf%3A0xafa66f9c8be3c91!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2jhu4cgVGjDtG5nIHRpbiAtIMSQSFFHIFRQLkhDTQ!5e0!3m2!1svi!2s!4v1701922033559!5m2!1svi!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
{% endblock contact_content%}

Django_project/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Trang chủ
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/home.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static "js/shop.js" %}"></script>
{% endblock link_content %}

{% block banner%}
    <div class="section_1" style="background-image: url('{% static 'image/background_img.png' %}');">
        <div class="row row_banner">
            <div class="col-sm-3">
                <h1 class="title_banner">Time to discover</h1>
                <p class="text_banner">text gi day</p>
                <button class="btn_banner">Khám phá</button>
                <div class="media_items_list">
                    <a class="media_item" href=""><i class="fa-brands fa-square-facebook"></i></a>
                    <a class="media_item" href=""><i class="fa-brands fa-square-instagram"></i></a>
                </div>
            </div>
            <div class="col-sm-6">
                <img src="{% static "image/img_02.png" %}" alt="img_banner" class="img_banner">
            </div>
            <div class="col-sm-3 col_right_banner">
                <div class="info_banner">
                    <h2>100%</h2>
                    <h3>Nature grades</h3>
                </div>
                <div class="info_banner">
                    <h2>100%</h2>
                    <h3>Nature grades</h3>
                </div>
                <div class="info_banner">
                    <h2>100%</h2>
                    <h3>Nature grades</h3>
                </div>
            </div>
        </div>
    </div>
{% endblock banner%}

{% block home_content%}
    <!-- CTA -->
    <div class="container section_3">
        <div class="row">
            <div class="col-sm-6">
                <h1>THERE IS ALL ABOUT CAFENOD COFFEE HOUSE</h1>
                <p class="text_cta">
                    From a cultural standpoint, coffeehouses largely serve as centers of social interaction: the coffeehouse provides patrons with a place to congregate, talk, read, write, entertain one another, or pass the time, whether individually or in small groups.
                    <br>
                    <br>
                    THERE IS ALL ABOUT OUR CAFENOD COFFEE SHOPS
                    The coffee is brewed by first roasting the green coffee beans over hot coals in a brazier. Once the beans are roasted each participant is given an opportunity to sample
                    <br>
                    <br>
                    THIS IS FOLLOWED BY THE GRINDING
                    The coffee is brewed by first roasting the green coffee beans over hot coals in a brazier. Once the beans are roasted each participant is given an opportunity to sample the aromatic smoke by wafting it towards them.
                </p>
                <button class="cta_btn">Đọc thêm</button>
            </div>
            <div class="col-sm-6">
                <img src="{% static "image/img_01.png" %}" alt="img_cta" class="img_cta">
            </div>
        </div>
    </div>

    <!-- Product -->
    <div class="container section_4">
        <div class="row row_title">
            <div class="col-sm-6">
                <h1>Our popular product</h1>
            </div>
            <div class="col-sm-6 col_btn_product">
                <form action="{% url 'shop_app:shop' %}" method="GET">
                    <button class="btn btn-outline-dark btn_product">Ghé thăm sản phẩm của chúng tôi</button>
                </form>
            </div>
        </div>
    </div>

    <div class="row row_product_1">
        {% for product in products|slice:":3" %}
        <div class="col-sm-4 col_product">
            <img src="{% static product.img_url %}" alt="img_product" class="img_product">
            <h4>{{product.product_name}}</h4>
            <div class="cost">${{ product.price }}</div>
            <button class="btn btn-outline-dark addToCart" data-product-id="{{ product.product_id }}" data-product-name="{{ product.product_name }}" data-product-price="{{ product.price }}" data-product-img="{{ product.img_url }}">Add to cart</button>
            <a href="{% url "product_app:product_detail" product.slug product.product_id%}">
                <button class="btn btn-outline-dark">Chi tiết sản phẩm</button>
            </a>
            <input type="button" value="-" class="btn decreaseBtn" data-product-id="{{ product.product_id }}">
            <input type="text" class="quantityInput" name="quantity" value="1" data-product-id="{{ product.product_id }}">
            <input type="button" value="+" class="btn increaseBtn" data-product-id="{{ product.product_id }}">
        </div>
        {% endfor %} 
    </div>

    <div class="row row_product_2">
        {% for product in products|slice:"3:6"%}
            <div class="col-sm-4 col_product">
                <img src="{% static product.img_url %}" alt="img_product" class="img_product">
                <h4>{{product.product_name}}</h4>
                <div class="cost">${{ product.price }}</div>
                <button class="btn btn-outline-dark addToCart" data-product-id="{{ product.product_id }}" data-product-name="{{ product.product_name }}" data-product-price="{{ product.price }}" data-product-img="{{ product.img_url }}">Add to cart</button>
                <a href="{% url "product_app:product_detail" product.slug product.product_id%}">
                    <button class="btn btn-outline-dark">Chi tiết sản phẩm</button>
                </a>
                <input type="button" value="-" class="btn decreaseBtn" data-product-id="{{ product.product_id }}">
                <input type="text" class="quantityInput" name="quantity" value="1" data-product-id="{{ product.product_id }}">
                <input type="button" value="+" class="btn increaseBtn" data-product-id="{{ product.product_id }}">
            </div>
        {% endfor %}
    </div>

    <!-- nhan xet cua nguoi dung  -->

    <!-- blogs  -->
    <div class="container section_5">
        <!-- icon  -->
        <h1 class="h1_blog">Blogs</h1>
        <div class="row row_blogs">
            <div class="col col_blogs_item">
                <a href=""><img src="{% static "image/Picture/cafe-vot-sai-gon-12-1024x1024.jpg" %}" alt="img_blogs" class="img_blogs"></a>
                <a class="title_blogs" href=""><h5>4 QUÁN CAFE VỢT SÀI GÒN TỒN TẠI HƠN NỬA THẾ KỶ AI CŨNG NÊN GHÉ ĐẾN MỘT LẦN</h5></a>
            </div>
            <div class="col col_blogs_item">
                <a href=""><img src="{% static "image/Picture/cafe-vot-sai-gon-9.jpg" %}" alt="img_blogs" class="img_blogs"></a>
                <a class="title_blogs" href=""><h5>LỊCH SỬ HÌNH THÀNH VÀ PHÁT TRIỂN CỦA CÀ PHÊ: SỰ TÁC ĐỘNG TO LỚN CỦA CÀ PHÊ ĐỐI VỚI CÁC NƯỚC CHÂU ÂU</h5></a>
            </div>
            <div class="col col_blogs_item">
                <a href=""><img src="{% static "image/Picture/cafe-vot-sai-gon-13.jpg" %}" alt="img_blogs" class="img_blogs"></a>
                <a class="title_blogs" href=""><h5>LỊCH SỬ HÌNH THÀNH VÀ PHÁT TRIỂN CỦA CÀ PHÊ: SỰ TÁC ĐỘNG TO LỚN CỦA CÀ PHÊ ĐỐI VỚI CÁC NƯỚC CHÂU ÂU</h5></a>
            </div>
        </div>
        <form action="{% url 'blog_app:blog' %}" method="GET">
            <button class="btn btn-outline-dark btn_blogs">See all blogs</button>
        </form>
    </div>
{% endblock home_content%}

Django_project/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block title_content%}
Chi tiết sản phẩm
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/product.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/shop.js' %}"></script>
{% endblock link_content %}

{% block product_content %}
<div class="product_container">
    <div class="col-sm-4 product">
        <img src="{% static product.img_url %}" alt="img_product" class="img_product">
        <h4>{{product.product_name}}</h4>
        <div class="cost">${{product.price}}</div>
        <button class="btn btn-outline-dark addToCart" data-product-id="{{ product.product_id }}" data-product-name="{{ product.product_name }}" data-product-price="{{ product.price }}" data-product-img="{{ product.img_url }}">Add to cart</button>
        <a href="{% url "shop_app:shop" %}">
            <button class="btn btn-outline-dark">Tiếp tục mua hàng</button>
        </a>
        <input type="button" value="-" class="btn decreaseBtn" data-product-id="{{ product.product_id }}">
        <input type="text" class="quantityInput" name="quantity" value="1" data-product-id="{{ product.product_id }}">
        <input type="button" value="+" class="btn increaseBtn" data-product-id="{{ product.product_id }}">
    </div>
</div>
{% endblock product_content %}

Django_project/templates/shop.html
{% extends 'base.html'%}
{% load static%}

{% block title_content%}
Sản phẩm
{% endblock title_content%}

{% block link_content%}
    <link rel="stylesheet" href="{% static "css/shop.css" %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static "js/shop.js" %}"></script>
{% endblock link_content %}

{%block shop_content%}
    <div class="container section_2">
        <div class="prouct_list">
            
            <div class="btn_list">
                <button type="button" name="All" class="btn_category" data-component="all">All</button>
                <button type="button" name="Robusta" class="btn_category" data-component="robusta">Robusta</button>
                <button type="button" name="Arabica" class="btn_category" data-component="arabica">Arabica</button>
                <button type="button" name="Culi" class="btn_category" data-component="culi">Culi</button>
            </div>

            <div class="product_container">
                {% for product in products %}
                <div class="col-sm-4 product">
                    <img src="{% static product.img_url %}" alt="img_product" class="img_product">
                    <h4>{{product.product_name}}</h4>
                    <div class="cost">${{product.price}}</div>
                    <button class="btn btn-outline-dark addToCart" data-product-id="{{ product.product_id }}" data-product-name="{{ product.product_name }}" data-product-price="{{ product.price }}" data-product-img="{{ product.img_url }}">Add to cart</button>
                    <a href="{% url "product_app:product_detail" product.slug product.product_id%}">
                        <button class="btn btn-outline-dark">Chi tiết sản phẩm</button>
                    </a>
                    <input type="button" value="-" class="btn decreaseBtn" data-product-id="{{ product.product_id }}">
                    <input type="text" class="quantityInput" name="quantity" value="1" data-product-id="{{ product.product_id }}">
                    <input type="button" value="+" class="btn increaseBtn" data-product-id="{{ product.product_id }}">
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{%endblock shop_content%}